make SPEEDYBEEF405MINI EXTRA_FLAGS="\
    -DCLOUD_BUILD\
    -DUSE_DSHOT\
    -DUSE_SERIALRX\
    -DUSE_SERIALRX_CRSF\
    -DUSE_TELEMETRY\
    -DUSE_TELEMETRY_CRSF\
    -DUSE_OSD\
    -DUSE_OSD_SD\
    -DUSE_PINIO\
    "
