make SPEEDYBEEF405MINI EXTRA_FLAGS="\
    -DCLOUD_BUILD\
    -DUSE_DSHOT\
    -DUSE_SERIALRX\
    -DUSE_SERIALRX_CRSF\
    -DUSE_TELEMETRY\
    -DUSE_TELEMETRY_CRSF\
    -DFSP_PERIOD_HZ=510\
    -DUSE_SERVOS=1\
    "
