make SPEEDYBEEF405MINI EXTRA_FLAGS="\
    -DCLOUD_BUILD\
    -DUSE_DSHOT\
    -DUSE_SERIALRX\
    -DUSE_SERIALRX_CRSF\
    -DUSE_TELEMETRY\
    -DUSE_TELEMETRY_CRSF\
    -DFSP_MAVLINK_TUNNEL_SIZE=2\
    -DFSP_PERIOD_HZ=500\
    "
