make SPEEDYBEEF7V3 EXTRA_FLAGS="\
    -DCLOUD_BUILD\
    -DUSE_DSHOT\
    -DUSE_SERIALRX\
    -DUSE_SERIALRX_MAVLINK\
    -DUSE_TELEMETRY\
    -DUSE_TELEMETRY_MAVLINK
    -DUSE_VTX\
    -DUSE_OSD\
    "
